#!/usr/bin/python
import os, sys, signal 
from time import sleep
from subprocess import Popen, PIPE
import abtserver.rpc_main

if __name__ == "__main__":
	
	try:
		if os.path.exists("/opt/abt") == False: # check for abt directory , if false then 
			try:
				print "creating abt and db directory and copying places.db to abt"
				os.system("mkdir -p /opt/abt/db") # create abt directory and db to host all databases
				os.system("mkdir -p /opt/abt/export")
				
				if os.path.exists("./src/places.db") == True:
					os.system("cp ./src/places.db /opt/abt/places.db") # copy places.db from /src to abt
				else:
					os.system("cp root/ABTcore/src/places.db /opt/abt/places.db") # copy places.db from /src to abt
				if os.path.exists("/opt/abt/adb") == False:
					print "copying adb"
					os.system("cp ./install/adb /opt/abt/adb") # copy adb from /install to abt
					os.system("sudo chmod 777 /opt/abt/adb")
					os.system("pwd")
					
					os.system("sudo cp ./doc /opt/abt/ -R")    

			except:
				print "can't create directory something is wrong"

		else:
		 	if os.path.exists("/opt/abt/db") == False: # check for abt/db directory , if false then
				try:
					print "creating db directory and copying places.db"
					os.system("mkdir /opt/abt/db") # create db directory in abt
					os.system("mkdir -p /opt/abt/export")
					if os.path.exists("./src/places.db") == True:
						os.system("cp ./src/places.db /opt/abt/places.db") # copy places.db from /src to abt
					else:
						os.system("cp root/ABTcore/src/places.db /opt/abt/places.db") # copy places.db from /src to abt
					if os.path.exists("/opt/abt/adb") == False:
						print "copying adb"
						os.system("cp ./install/adb /opt/abt/adb") # copy adb from /install to abt
						os.system("sudo chmod 777 /opt/abt/adb")
						os.system("sudo cp ./doc /opt/abt/ -R")    
				except:
					print "can't create directory something is wrong"
			else:
				print "db already exist"
				
			print "abt already exist"
		
		if os.path.exists("/opt/abt/ABT.apk") == False: # check for abt/db directory , if false then
			os.system("cp ./install/ABT.apk /opt/abt/") # copy ABT.apk from /install to abt

		if os.path.exists("/opt/abt/doc") == True: # check for abt/db directory , if false then
			os.system("rm -rf ./doc") # copy ABT.apk from /install to abt
			
		abtserver.rpc_main.runabt()

		
	except:
		print "inside exception"
		
